//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Script1.rc
//
#define ID_EXIT                         001
#define ID_FILENEW                      10
#define ID_FILEOPEN                     20
#define ID_FILECLOSE                    30
#define ID_COPY                         60
#define ID_HELPCONTENT                  101
#define ID_ABOUT                        102
#define ID_D1                           211
#define ID_D2                           212
#define ID_D3                           213
#define ID_D4                           214
#define ID_D5                           215
#define ID_D6                           216
#define ID_D7                           217
#define ID_D8                           218
#define ID_D9                           219
#define ID_F1                           220
#define ID_F2                           221
#define ID_F3                           222
#define ID_F4                           223
#define ID_F5                           224
#define ID_F6                           225
#define ID_F7                           226
#define ID_F8                           227
#define ID_F9                           228
#define ID_F10                          229
#define ID_F11                          230
#define ID_F12                          231
#define ID_F13                          232
#define ID_CALCULATE                    301
#define ID_FIT                          302
#define ID_FASTFIT                      303
#define ID_CALCULATE_SAVE               310
#define ID_CALCULATE_RESULTS            320
#define ID_CALCULATE_RESULTSE           321
#define ID_CALCULATE_VECTORS            330
#define ID_CALCULATE_VECTORSN           331
#define ID_CALCULATE_VECTORS2           335
#define ID_CTERMSALL                    340
#define ID_CTERMSINCLUDED               345
#define ID_CADD                         350
#define ID_CADDALL                      351
#define ID_CREMOVE                      352
#define ID_CREMOVEALL                   353
#define ID_CSTATICNAME                  360
#define ID_FIT_ACCURACY                 361
#define ID_ZEEMAN_G                     370
#define ID_PFREEION_NEW                 501
#define ID_PFREEION_OPEN                502
#define ID_PSAVE                        503
#define ID_PAD_NEW                      504
#define ID_PAD_OPEN                     505
#define ID_PFSTATICNAME                 515
#define ID_PF2                          521
#define ID_PF4                          522
#define ID_PF6                          523
#define ID_PFDZETA                      524
#define ID_PCR_NEW                      540
#define ID_PCR_OPEN                     541
#define ID_FIELD_CALCULATE              542
#define ID_PCR20                        550
#define ID_PCR21                        551
#define ID_PCR22                        552
#define ID_PCR23                        553
#define ID_PCR24                        554
#define ID_PCR40                        560
#define ID_PCR41                        561
#define ID_PCR42                        562
#define ID_PCR43                        563
#define ID_PCR44                        564
#define ID_PCR45                        565
#define ID_PCR46                        566
#define ID_PCR47                        567
#define ID_PCR48                        568
#define ID_PCR60                        570
#define ID_PCR61                        571
#define ID_PCR62                        572
#define ID_PCR63                        573
#define ID_PCR64                        574
#define ID_PCR65                        575
#define ID_PCR66                        576
#define ID_PCR67                        577
#define ID_PCR68                        578
#define ID_PCR69                        579
#define ID_PCR70                        580
#define ID_PCR71                        581
#define ID_PCR72                        582
#define ID_PCR_TASKNAME                 590
#define ID_MATRIX                       601
#define ID_MQUERY                       604
#define ID_MLIST1                       610
#define ID_MLIST2                       620
#define ID_MLIST3                       630
#define ID_MATRIXVALUE                  640
#define ID_MUPDATE                      650
#define ID_SHOWCMD                      665
#define ID_ENERGY_LEVELS                680
#define ID_OPTIONS                      710
#define ID_ONAME                        712
#define ID_ONORMW                       713
#define ID_ONORMS                       714
#define ID_OTERMSSEL                    720
#define ID_OVECT                        730
#define ID_OVECTNUMB                    732
#define ID_OENERGY                      734
#define ID_OENERGY2                     735
#define ID_FILETREENEDIT1               1010
#define ID_PROGRESSE                    1010
#define ID_FILETREENEDIT2               1020
#define ID_PROGRESSM                    1020
#define ID_FILETREENEDIT3               1030
#define ID_PROGRESSC                    1030
#define IDC_LIST1                       1079
#define ID_SETTING_SAVE                 1110
#define ID_LICENSE                      1111
#define ID_DISCLAIMER                   1112
#define IDC_PAR1                        1201
#define IDC_PAR2                        1202
#define IDC_PAR3                        1203
#define IDC_PAR4                        1204
#define IDC_PAR5                        1205
#define IDC_PAR6                        1206
#define IDC_PAR7                        1207
#define IDC_PAR8                        1208
#define IDC_PAR9                        1209
#define IDC_PARM1                       1211
#define IDC_PARM2                       1212
#define IDC_PARM3                       1213
#define IDC_PARM4                       1214
#define IDC_PARM5                       1215
#define IDC_RADIO_CF1                   1251
#define IDC_RADIO_CF2                   1252
#define IDC_RADIO_CF3                   1253
#define IDC_RADIO_CF4                   1254
#define IDC_RADIO_CF5                   1255
#define IDC_PARC                        1260
#define ID_FILETREECOMBO                2010
#define ID_FILETREELIST1                2020
#define ID_FILETREELIST2                2030
#define ID_FILETREEDIT                  2040
#define ID_FILETREECHANGE               2041
#define ID_FILETREECHECK                2050
#define ID_FILETREECOPY                 2060
#define ID_FILETREENELEC                2070
#define ID_FILETREEDELETE               2080
#define ID_STOPIT                       3000
#define IDL_DATAFIT                     3021
#define ID_FITTING_ACCURACYOENERGY      3027
#define ID_PA                           5010
#define ID_PBE                          5011
#define ID_PGA                          5012
#define ID_PM0                          5101
#define ID_PM2                          5102
#define ID_PM4                          5103
#define ID_PP2                          5104
#define ID_PP4                          5105
#define ID_PP6                          5106
#define IDC_EDIT1                       11111
#define IDC_SLIDER1                     22222
#define ID_JUDDOFELT                    40040
#define ID_ESRSPECTRUM                  40041
#define ID_PT2                          50002
#define ID_PT3                          50003
#define ID_PT4                          50004
#define ID_PT6                          50005
#define ID_PT7                          50006
#define ID_PT8                          50007
#define IDL_SITE                        54210
#define ID_SELECTTITLE                  54220
#define ID_SELECTRE                     54221
#define ID_LIGAND                       54222
#define ID_GPAR                         54230
#define ID_MTEXT1                       60101
#define ID_MTEXT2                       60102
#define ID_MTEXT3                       60103
#define ID_MRESULT1                     60201
#define ID_MRESULT2                     60202
#define ID_MRESULT3                     60203
#define ID_MJLIST                       60300
#define ID_PASSWORD                     -666
#define IDC_SCROLLBAR1                  -333
#define IDC_SLIDER3                     -222
#define IDC_SLIDER2                     -111

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         40045
#define _APS_NEXT_CONTROL_VALUE         1119
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
